# Generated by Django 2.2.2 on 2019-06-22 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('sku', models.CharField(max_length=25)),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('type', models.CharField(choices=[('T1', 'Type 01'), ('T2', 'Type 02'), ('T3', 'Type 03'), ('T4', 'Type 04')], default='T1', max_length=2)),
            ],
        ),
    ]
